[world]
name = "Coin Flip"
description = "A simple coin flip prediction game to learn Dojo development. Players predict heads or tails and track their wins and losses."
seed = "coin_flip"

[namespace]
default = "coin_flip"

[env]
rpc_url = "http://localhost:5050/"
# Default account for katana with seed = 0
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"

[writers]
"coin_flip" = ["coin_flip-actions"]
